### ISSUE TITLE
Bluetooth Audio Stutter Issue

### ISSUE THREAD

**Issue by admiskandar** [vietthai2512/HP_Pavilion_15_cs0101TX_Hackintosh#1]
Hi! I would like to say thank you so much for this EFI! Everything works perfectly fine. 

One small issue: When I try to connect AirPods Pro (Bluetooth Device) the sound stutter a lot. This only happen when I use both WiFi and Bluetooth at the same time. Do you know if there is any fix to this?

**Comment by vietthai2512** [comment]
That may be an issue caused by wireless interference. You should use 5Ghz wifi. Further reading: https://support.apple.com/en-us/HT201542
