### ISSUE TITLE
[Question] UHD 620 Compatibility/Fixes

### ISSUE THREAD

**Issue by jasonmerc** [vietthai2512/HP_Pavilion_15_cs0101TX_Hackintosh#6]
Hello,

This issue I opened is not an actual issue, moreso just a question.  On your HP, you got UHD 620 graphics to work with MacOS.  I'm running an HP Notebook 17 x115dx, which has a kaby lake i7, but it does have a UHD 620 as well.  I cannot get any output to my laptop's internal LCD panel on anything above High Sierra, no matter what I do/try.  I swear I've followed every guide out there and nothing's worked.  Every time it gets past opencore logs, the screen just goes all black when there's supposed to be the Apple logo.  The backlight works mind you, it's just a blank screen.  Nothing in the open core logs seem to indicate what could be wrong.

Your laptop is not the same but seems "similar enough" to mine, so I just wanted to ask you what you did to get UHD 620 graphics working for OS 10.14+ on your HP laptop (or in your case OS 11).

Thank you in advance

**Comment by vietthai2512** [comment]
I built my EFI a long time ago so I don't remember how did I make it work, I think you should rebuild your EFI by following Dortania's guide https://dortania.github.io/OpenCore-Install-Guide/

**Comment by jasonmerc** [comment]
Yes I did do that, followed the guide exactly.  Still ran into issues.  The guide did not have any advice for fixing this.
